[oobe]
command=/etc/oobe.sh
defaultUid=1000
defaultName = SamLinux

[shortcut]
enabled = true
icon = /usr/lib/wsl/samlinux.ico

[windowsterminal]
enabled = true
ProfileTemplate = /usr/lib/wsl/terminal-profile.json
